package kr.co.demo.core.storage.annotation;

import java.lang.annotation.*;

/**
 * 도메인 객체의 식별자(ID) 필드를 지정합니다.
 *
 * <p>사용 예시:
 * <pre>{@code
 * @StorageTable("orders")
 * public class Order {
 *
 *     @StorageId
 *     private Long id;  // DB가 자동 생성
 * }
 *
 * @StorageTable("products")
 * public class Product {
 *
 *     @StorageId(autoGenerated = false)
 *     private String sku;  // 애플리케이션이 직접 할당
 * }
 * }</pre>
 */
@Documented
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface StorageId {

	/**
	 * ID 자동 생성 여부
	 * <p>
	 * true: DB가 자동 생성 (AUTO_INCREMENT, SERIAL 등)
	 * false: 애플리케이션이 직접 할당
	 *
	 * @return 자동 생성 여부 (기본값: true)
	 */
	boolean autoGenerated() default true;
}
