package kr.co.demo.core.storage;

import static org.assertj.core.api.Assertions.assertThat;

import kr.co.demo.core.storage.annotation.*;
import kr.co.demo.core.storage.enums.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AnnotationTest {

	@StorageTable("test_table")
	@StorageIndex(name = "idx_a", columns = {"col_a"})
	@StorageIndex(name = "idx_b", columns = {"col_b", "col_c"}, unique = true)
	@StorageJoin(target = Object.class, type = JoinType.LEFT, on = "t.id = j.t_id")
	static class TestDomain {

		@StorageId
		private Long id;

		@StorageCompositeId
		private String partA;

		@StorageColumn(value = "custom_col", nullable = false, unique = true)
		private String name;

		@StorageEnum(EnumType.STRING)
		private String enumField;

		@StorageRelation(type = RelationType.ONE_TO_MANY, mappedBy = "parent",
				cascade = CascadeType.ALL, fetch = FetchType.LAZY)
		private Object children;

		@StorageTransient
		private String temp;

		@StorageVersion
		private Long version;

		@StorageCreatedAt
		private Object created;

		@StorageUpdatedAt
		private Object updated;

		@StorageCall(name = "sp_test", resultType = String.class)
		void testMethod() {}
	}

	@Test
	@DisplayName("@StorageTable 속성")
	void storageTable() {
		StorageTable ann = TestDomain.class.getAnnotation(StorageTable.class);
		assertThat(ann.value()).isEqualTo("test_table");
	}

	@Test
	@DisplayName("@StorageIndex 복수 어노테이션")
	void storageIndex() {
		StorageIndex[] indexes = TestDomain.class.getAnnotationsByType(StorageIndex.class);
		assertThat(indexes).hasSize(2);
		assertThat(indexes[0].name()).isEqualTo("idx_a");
		assertThat(indexes[0].unique()).isFalse();
		assertThat(indexes[1].columns()).containsExactly("col_b", "col_c");
		assertThat(indexes[1].unique()).isTrue();
	}

	@Test
	@DisplayName("@StorageJoin 속성")
	void storageJoin() {
		StorageJoin[] joins = TestDomain.class.getAnnotationsByType(StorageJoin.class);
		assertThat(joins).hasSize(1);
		assertThat(joins[0].type()).isEqualTo(JoinType.LEFT);
		assertThat(joins[0].on()).isEqualTo("t.id = j.t_id");
	}

	@Test
	@DisplayName("@StorageId 속성")
	void storageId() throws Exception {
		StorageId ann = TestDomain.class.getDeclaredField("id")
				.getAnnotation(StorageId.class);
		assertThat(ann).isNotNull();
		assertThat(ann.autoGenerated()).isTrue();
	}

	@Test
	@DisplayName("@StorageCompositeId 존재")
	void compositeId() throws Exception {
		assertThat(TestDomain.class.getDeclaredField("partA")
				.isAnnotationPresent(StorageCompositeId.class)).isTrue();
	}

	@Test
	@DisplayName("@StorageColumn 속성")
	void storageColumn() throws Exception {
		StorageColumn ann = TestDomain.class.getDeclaredField("name")
				.getAnnotation(StorageColumn.class);
		assertThat(ann.value()).isEqualTo("custom_col");
		assertThat(ann.nullable()).isFalse();
		assertThat(ann.unique()).isTrue();
	}

	@Test
	@DisplayName("@StorageEnum 속성")
	void storageEnum() throws Exception {
		StorageEnum ann = TestDomain.class.getDeclaredField("enumField")
				.getAnnotation(StorageEnum.class);
		assertThat(ann.value()).isEqualTo(EnumType.STRING);
	}

	@Test
	@DisplayName("@StorageRelation cascade/fetch 속성")
	void storageRelation() throws Exception {
		StorageRelation ann = TestDomain.class.getDeclaredField("children")
				.getAnnotation(StorageRelation.class);
		assertThat(ann.type()).isEqualTo(RelationType.ONE_TO_MANY);
		assertThat(ann.mappedBy()).isEqualTo("parent");
		assertThat(ann.cascade()).containsExactly(CascadeType.ALL);
		assertThat(ann.fetch()).isEqualTo(FetchType.LAZY);
	}

	@Test
	@DisplayName("@StorageTransient 존재")
	void storageTransient() throws Exception {
		assertThat(TestDomain.class.getDeclaredField("temp")
				.isAnnotationPresent(StorageTransient.class)).isTrue();
	}

	@Test
	@DisplayName("@StorageVersion 존재")
	void storageVersion() throws Exception {
		assertThat(TestDomain.class.getDeclaredField("version")
				.isAnnotationPresent(StorageVersion.class)).isTrue();
	}

	@Test
	@DisplayName("@StorageCreatedAt 존재")
	void storageCreatedAt() throws Exception {
		assertThat(TestDomain.class.getDeclaredField("created")
				.isAnnotationPresent(StorageCreatedAt.class)).isTrue();
	}

	@Test
	@DisplayName("@StorageUpdatedAt 존재")
	void storageUpdatedAt() throws Exception {
		assertThat(TestDomain.class.getDeclaredField("updated")
				.isAnnotationPresent(StorageUpdatedAt.class)).isTrue();
	}

	@Test
	@DisplayName("@StorageCall 속성")
	void storageCall() throws Exception {
		StorageCall ann = TestDomain.class.getDeclaredMethod("testMethod")
				.getAnnotation(StorageCall.class);
		assertThat(ann.name()).isEqualTo("sp_test");
		assertThat(ann.resultType()).isEqualTo(String.class);
	}

	@Test
	@DisplayName("CascadeType enum 값 전부 존재")
	void cascadeTypes() {
		assertThat(CascadeType.values()).containsExactly(
				CascadeType.ALL, CascadeType.PERSIST, CascadeType.MERGE,
				CascadeType.REMOVE, CascadeType.REFRESH, CascadeType.DETACH);
	}

	@Test
	@DisplayName("FetchType enum 값 전부 존재")
	void fetchTypes() {
		assertThat(FetchType.values()).containsExactly(
				FetchType.DEFAULT, FetchType.LAZY, FetchType.EAGER);
	}

	@Test
	@DisplayName("JoinType enum 값 전부 존재")
	void joinTypes() {
		assertThat(JoinType.values()).containsExactly(
				JoinType.INNER, JoinType.LEFT, JoinType.RIGHT,
				JoinType.FULL, JoinType.CROSS);
	}

	@Test
	@DisplayName("DialectType enum 값 전부 존재")
	void dialectTypes() {
		assertThat(DialectType.values()).containsExactly(
				DialectType.MYSQL, DialectType.POSTGRES,
				DialectType.ORACLE, DialectType.H2);
	}
}
